### PR TITLE
change drawer opt out links for different devices

### PR DESCRIPTION
**Pull request by leggsimon**
@i-like-robots

### CODE REVIEW

**Comment by matthew-andrews** [comment]
sadly, no :'(

**Comment by i-like-robots** [comment]
warum?

**Comment by matthew-andrews** [comment]
the logic is really quite complicated…

the web app / android app buttons are added on the client side (and the original opt out button removed — this probably could/should be tidied up to use the `forceOptInDevice` option only, but currently isn't) dependent on JavaScript UA sniffing:-
https://github.com/Financial-Times/n-ui/blob/master/welcome-message/new/index.js and the `forceOptInDevice` is ALSO respected so that the opt out button is hidden from old em dot devices……

**Comment by matthew-andrews** [comment]
to get this shipped it's probably wise to just not have these buttons here for now :-/

**Comment by matthew-andrews** [comment]
i don't mind taking responsibility for tidying this up and putting them back here at some point next week…

**Comment by i-like-robots** [comment]
The welcome-message JS takes effect on these buttons too, so this and the welcome message behave the same =]

**Comment by leggsimon** [comment]
Nah m8 ur rong

**Comment by i-like-robots** [comment]
🚀

**Comment by matthew-andrews** [comment]
😱 

ya this needs some tlc

**Comment by matthew-andrews** [comment]
but +1

**Pull request merged**
