### PR TITLE
Added subscribe link

### PR DESCRIPTION
**Pull request by adamsilver**

### CODE REVIEW

**Comment by aintgoin2goa** [comment]
What's the plan for small screens here?

**Comment by adamsilver** [comment]
Urgh, I see what you mean.  Had thought it would be fine taking the place of "My account" but currently "My Account" is hidden on small screens :(

**Comment by adamsilver** [comment]
Regardless you can merge as it won't show after merge due to lack of view model property.

**Comment by aintgoin2goa** [comment]
I'm not convinced about putting it here, tbh.  I get that it's the most obvious place but there just isn't room for it here.  Could we place it outside the nav, maybe just below it or something?

**Comment by adamsilver** [comment]
As per next-dev slack channel - Mattijas is happy to have this in for now like this, rather than have a missing feature on small screens.

**Pull request merged**
