### PR TITLE
Offset menu if markets data is displayed

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Fixes Financial-Times/next-front-page#327

### CODE REVIEW

**Comment by charypar** [comment]
:+1: Although, we'll have to revisit if we have some other content up there that's a different height...

**Comment by ironsidevsquincy** [comment]
Yes, it is brittle, it would also have to change if the header height changed. Not sure how else to make the menu full height/width without using `fixed` though.

Having said that, forgot about http://caniuse.com/#feat=viewport-units

**Comment by charypar** [comment]
It needs some markup changes that were prevented by the toggle with the old one. Now we have more freedom to change things I think...

**Comment by ironsidevsquincy** [comment]
https://github.com/Financial-Times/n-header-footer/issues/111

**Pull request merged**
