### PR TITLE
Update the build

### PR DESCRIPTION
**Pull request by TheoLeanse**
@andygout

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Probably also worth testing CSS and JS; add

```
.eslintrc.js
.scss-lint.yml
```

to the `.gitignore`

**Comment by andygout** [comment]
Looks good. And seems we do not need to add `n-heroku-tools` to the Makefile as everything is done by n-Makefile?

**Comment by TheoLeanse** [comment]
@ironsidevsquincy have added CSS and JS linting & fixed linting errors
@andygout nope don't think we need `n-heroku-tools` in here.

Do we need to bump a component's version if only updating build stuff?

**Comment by ironsidevsquincy** [comment]
Source has changed a bit too, so might as well do a patch release

👍

**Comment by TheoLeanse** [comment]
OK I shall do that then

**Pull request merged**
