### PR TITLE
Remove signupOrSubscribeMobile flag

### PR DESCRIPTION
**Pull request by lc512k**
@wheresrhys @ifyio

### CODE REVIEW

**Comment by i-like-robots** [comment]
Can this be closed or is it still relevant @lc512k?

**Comment by lc512k** [comment]
@i-like-robots seems this one slipped through the cracks. That flag is gone. I'll update the branch

**Comment by i-like-robots** [comment]
Probably no longer needed since we shipped the new header but no harm in merging =]

**Comment by lc512k** [comment]
Thanks @i-like-robots! Yeah, makes sense. Where does the new header live? Still catching up post-bootcamp...

**Comment by i-like-robots** [comment]
Currently it's in the `header_new` directory but it will be upstreamed into Origami within the next week or so.

**Pull request merged**
